### ISSUE TITLE
Utilité

### ISSUE THREAD

**Issue by Dan149** [paxo-rch/teensinAI_equipe6#1]
Le site est bien codé, simple et intuitif d'utilisation, rien à redire sur ce point de vue.
Néanmoins, l'idée selon laquelle "on pourrait utiliser plus d'énergie verte à un moment précis de la journée" est fausse:
lorsque de l'électricité est produite (à l'aide d'une centrale, d'éoliennes, de panneaux photovoltaïques...), celle-ci est stockée dans des accumulateurs, donc "unifié". Il n'est donc pas possible d'utiliser plus d'une source d'énergie que d'une autre à un moment précis de la journée, à mois que de nouveaux équipements d'énergie verte ne soient installés en même temps.
Ce projet reste tout de même un bon moyen d'introduction au webdev, et peut facilement être converti en portfolio d'équipe de dev.

**Comment by paxo-rch** [comment]
Mdr pourquoi tu fouilles mon GitHub

**Comment by Dan149** [comment]
> Mdr pourquoi tu fouilles mon GitHub

Tkt, je me promène.
